# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY  # This fixes the logging error

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/video-processor', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/video-processor']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'video-processor'
      - '--image'
      - 'gcr.io/$PROJECT_ID/video-processor'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '1800s'
      - '--concurrency'
      - '1'

images:
  - 'gcr.io/$PROJECT_ID/video-processor'

timeout: '1800s'